name: Publish Extension

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b525c5a8446c685325700831b63 # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@39370e3936379716fcee9ce392f6090c464116ea6 # v4.1.0
        with:
          node-version: "22"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Publish to Visual Studio Marketplace
        run: npx --yes @vscode/vsce@3.2.1 publish -p "${{ secrets.VSCE_PAT }}"
